//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEClinicsWebsite.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medico
    {
        public int ID { get; set; }
        public int EspecialidadeID { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public int Sexo { get; set; }
        public string Pais { get; set; }
        public string Provincia { get; set; }
        public string Endereco { get; set; }
        public string Telefone { get; set; }
        public string TelefoneAlternativo { get; set; }
        public string Email { get; set; }
        public string GrupoSanguineo { get; set; }
    
        public virtual Especialidade Especialidade { get; set; }
    }
}
